[[redirects]]
from = "/Projects"
to = "/projects"
status = 301
force = true

[[redirects]]
from = "/OurTeam"
to = "/our-team"
status = 301
force = true

[[redirects]]
from = "/WeNeedYou"
to = "/we-need-you"
status = 301
force = true

[[redirects]]
from = "/Documents"
to = "/documents"
status = 301
force = true

# API bypass (ať ho nechytá trailing slash canonicalization)
[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

# trailing slash removal
[[redirects]]
from = "/*/"
to = "/:splat"
status = 301
force = true